// <auto-generated />
namespace WebLibraryApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingSeed1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingSeed1));
        
        string IMigrationMetadata.Id
        {
            get { return "202301022217114_addingSeed1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
